---
version: '3.1'
services:

  db:
    restart: always
    image: postgres:15
    container_name: pg-l0
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes: [ postgresdata:/var/lib/postgresql/data ]
    ports: [ 5432:5432 ]

  nats:
    restart: always
    image: nats-streaming:0.25
    container_name: nats_streaming
    ports: [ 4222:4222, 8222:8222 ]
    expose: [ 4222 ]
    
volumes:
  postgresdata:
